#!/usr/bin/env python3
"""Count the physical source lines selected by the formal-interface appendix."""
import argparse
from collections import OrderedDict
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
APPENDIX = ROOT / "appendix-formal-interface-excerpts.tex"
SHORT_NAMES = {
    "Approximate Homomorphic Encryption Scheme Interface": "Scheme interface",
    "Metric Charts": "Metric charts",
    "Probability-One (Support-Level) Correctness": "Probability-one correctness",
    "Discrete-Gaussian Distribution and KL Formula": "Gaussian distribution and KL formula",
    "Product Samplers and SSProve Bridge": "Product samplers and SSProve bridge",
    "IND-CPA Game": "IND-CPA game",
    "IND-CPA with Decryption Oracle and Game": "IND-CPAD oracles and game",
    "Noise-Flooded Construction": "Noise-flooded construction",
    "Concrete IND-CPA Reduction": "Concrete IND-CPA reduction",
    "Loss Formula": "Loss formula",
    "Reduction Validity": "Reduction validity",
    "Miscellaneous Specification Helpers": "Miscellaneous specification helpers",
}


HELPER_NAMES = {
    "Schemes/ApproxFHE.v": "Scheme labels and package wrapper",
    "Schemes/Utils/IntVec.v": "Vector norm, zero, subtraction, and distance",
    "LibExtras/MathcompExtras/ListExtras.v": "Safe table indexing (`nth_valid`)",
    "LibExtras/SSProveExtras/ChoiceVector.v": "SSProve vector type (`chVec`)",
    "Schemes/Indcpa.v": "IND-CPA labels, locations, and interfaces",
    "Schemes/Indcpad.v": "IND-CPAD labels, locations, and interfaces",
    "Security/IndcpadSimulator.v": "Simulator interfaces, vector conversions, and location wrapper",
    "Probability/KL/Core.v": "KL divergence definition",
    "Security/NoiseFloodingSecurity/Final.v": "Theorem parameters, reduction/bound wrappers, and main theorem",
    "Security/NoiseFloodingSecurity/GaussianBasics.v": "Game and simulator module aliases",
    "Security/NoiseFloodingSecurity/Prelude.v": "Noise-flooding security result interface",
}


def measure(detailed=False):
    # The source uses explicit firstline/lastline bounds for each listing.
    pattern = r"\\subsection\{([^}]+)\}|\\inputminted\[(.*?)\]\{coq\}\{([^}]+)\}"
    sections = OrderedDict()
    selected = set()
    files = set()
    excerpts = 0
    current = None
    helpers = OrderedDict()
    for match in re.finditer(pattern, APPENDIX.read_text(), re.S):
        if match[1]:
            current = match[1]
            sections[current] = 0
            continue
        options, filename = match[2], match[3]
        first = int(re.search(r"firstline\s*=\s*(\d+)", options)[1])
        last = int(re.search(r"lastline\s*=\s*(\d+)", options)[1])
        source = (ROOT / filename).read_text().splitlines()
        if current is None or not 1 <= first <= last <= len(source):
            raise ValueError(f"Invalid excerpt: {filename}:{first}-{last}")
        lines = {(filename, n) for n in range(first, last + 1)}
        if selected & lines:
            raise ValueError(f"Overlapping excerpt: {filename}:{first}-{last}")
        selected.update(lines)
        files.add(filename)
        excerpts += 1
        sections[current] += len(lines)
        if current == "Miscellaneous Specification Helpers":
            relative = filename.removeprefix("rocq-excerpts/theories/")
            helpers.setdefault(relative, []).append((first, last))
    if excerpts != APPENDIX.read_text().count("\\inputminted["):
        raise ValueError("An inputminted listing was not counted")
    if detailed:
        return sections, excerpts, len(files), helpers
    return sections, excerpts, len(files)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--latex", action="store_true", help="emit the manuscript table")
    parser.add_argument("--detailed", action="store_true",
                        help="split miscellaneous helpers and show their source ranges in Markdown")
    args = parser.parse_args()
    if args.latex and args.detailed:
        parser.error("--detailed produces Markdown; use it without --latex")
    sections, excerpts, files = measure()
    total = sum(sections.values())
    if args.latex:
        print("% Generated by scripts/count-interface-excerpts.py --latex; do not edit counts.")
        print(r"\newcommand{\FormalExcerptLineCount}{" + str(total) + "}")
        print(r"\newcommand{\FormalExcerptListingCount}{" + str(excerpts) + "}")
        print(r"\newcommand{\FormalExcerptFileCount}{" + str(files) + "}")
        print(r"\begin{table}[H]")
        print(r"\centering")
        print(r"\caption{Size of the selected formal-interface excerpts. Counts are physical")
        print(r"Rocq source lines in inclusive \texttt{firstline}--\texttt{lastline} ranges,")
        print(r"including blank and comment lines; typeset wrapping is not counted.}")
        print(r"\label{tab:formal-excerpt-size}")
        print(r"\footnotesize")
        print(r"\begin{tabular}{@{}p{0.78\columnwidth}r@{}}")
        print(r"\toprule")
        print(r"Excerpt category & Source lines \\")
        print(r"\midrule")
        for section, count in sections.items():
            print(f"{SHORT_NAMES[section]} & {count} " + r"\\")
        print(r"\midrule")
        print(r"\textbf{Total} & \textbf{" + str(total) + r"} \\")
        print(r"\bottomrule")
        print(r"\end{tabular}")
        print(r"\end{table}")
    else:
        print("| Specification | Source lines |")
        print("|---|---:|")
        if args.detailed:
            groups = [
                ("Scheme / charts / correctness", ["Scheme interface", "Metric charts", "Probability-one correctness"]),
                ("Gaussian / sampler bridge", ["Gaussian distribution and KL formula", "Product samplers and SSProve bridge"]),
                ("Security games", ["IND-CPA game", "IND-CPAD oracles and game"]),
                ("Flooded construction", ["Noise-flooded construction"]),
                ("Concrete reduction", ["Concrete IND-CPA reduction"]),
                ("Loss / reduction validity", ["Loss formula", "Reduction validity"]),
                ("Misc. helpers", ["Miscellaneous specification helpers"]),
            ]
            counts = {SHORT_NAMES[section]: count for section, count in sections.items()}
            if sorted(name for _, names in groups for name in names) != sorted(counts):
                raise ValueError("Summary groups do not cover each category exactly once")
            for label, names in groups:
                print(f"| {label} | {sum(counts[name] for name in names)} |")
        else:
            for section, count in sections.items():
                print(f"| {SHORT_NAMES[section]} | {count} |")
        print(f"| **Total** | **{total}** |")
        print(f"\n{excerpts} non-overlapping excerpts across {files} source files.")
        if args.detailed:
            _, _, _, helpers = measure(detailed=True)
            print("\nMiscellaneous helpers (source ranges are inclusive, relative to `theories/`):\n")
            print("| Helper group | Source | Ranges | Source lines |")
            print("|---|---|---|---:|")
            helper_total = 0
            for filename, ranges in helpers.items():
                size = sum(last - first + 1 for first, last in ranges)
                helper_total += size
                bounds = ", ".join(f"{first}–{last}" for first, last in ranges)
                source = f"[{Path(filename).name}](theories/{filename})"
                print(f"| {HELPER_NAMES[filename]} | {source} | {bounds} | {size} |")
            if helper_total != sections["Miscellaneous Specification Helpers"]:
                raise ValueError("Helper breakdown does not match subtotal")
            print(f"| **Total misc. helpers** | | | **{helper_total}** |")



if __name__ == "__main__":
    main()
